version: '3.8'

services:
  app:
    build: .
    container_name: tom_storytelling
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MONGO_URL=${MONGO_URL}
    volumes:
      - ./user_images:/app/user_images
    restart: unless-stopped
